In [14]:
"""Numpy samples
"""
import numpy as np

arr = np.array(
  [1, 2, 3]
)

arr_2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

array([ 0,  5, 10, 15])

In [2]:
arr

array([1, 2, 3])

In [3]:
arr_2

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
# show what kind of array
arr.shape

(3,)

In [5]:
arr_2.shape

(2, 3)

In [6]:
# find out how many dimensions the array has
arr.ndim

1

In [7]:
arr_2.ndim

2

In [8]:
# show data type of the array contents
arr_2.dtype

dtype('int64')

In [9]:
# show number of units
arr_2.size

6

In [17]:
# an arithmetic progression with an initial term of 0, a terminal term of 20, and a common difference of 5.
np.arange(0, 20, 5)

array([ 0,  5, 10, 15])

In [18]:
np.arange(0, 3, 0.4)

array([0. , 0.4, 0.8, 1.2, 1.6, 2. , 2.4, 2.8])

In [20]:
# an array consisting only of numbers 0 through
np.zeros(
  (2, 3)
)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.zeros(
    (2, 3),
    dtype=np.int16
)


array([[0, 0, 0],
       [0, 0, 0]], dtype=int16)

In [22]:
# an array consisting only of numbers 1 through
np.ones(
    (2, 3),
    dtype=np.int16
)


array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [24]:
# create an array with the number of elements specified in the third argument, with equally spaced common difference
np.linspace(0, 20, 7)

array([ 0.        ,  3.33333333,  6.66666667, 10.        , 13.33333333,
       16.66666667, 20.        ])

In [27]:
"""Edit array
"""
init_arr = np.arange(6)
init_arr

array([0, 1, 2, 3, 4, 5])

In [29]:
# convert the array dimension
reshaped_arr = init_arr.reshape(2, 3)
reshaped_arr


array([[0, 1, 2],
       [3, 4, 5]])

In [31]:
# T attribute: swap rows and columns of an array
reshaped_arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [38]:
# bind arrays
arr_x = np.arange(0, 10 ,2)
arr_y = np.arange(5)
arr_z = np.arange(0, 100, 20)
print(
    arr_x,
    arr_y,
    arr_z
)

[0 2 4 6 8] [0 1 2 3 4] [ 0 20 40 60 80]


In [37]:
np.append(arr_x, arr_y)

array([0, 2, 4, 6, 8, 0, 1, 2, 3, 4])

In [39]:
# stack arrays vertically
np.vstack([
    arr_x,
    arr_y,
    arr_z
])

array([[ 0,  2,  4,  6,  8],
       [ 0,  1,  2,  3,  4],
       [ 0, 20, 40, 60, 80]])

In [40]:
# stack arrays horizontally
np.hstack([
    arr_x,
    arr_y,
    arr_z
])


array([ 0,  2,  4,  6,  8,  0,  1,  2,  3,  4,  0, 20, 40, 60, 80])